# Generated by Django 5.1.2 on 2024-10-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_model_app', '0003_author_alter_task_user_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='books',
            new_name='author',
        ),
    ]
